version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      - DB_PASS=postgres
      - DB_HOST=db
    depends_on:
      - db
    command:
      - ./run.sh
volumes:
  postgres-data:
